### ISSUE TITLE
MQTT Protocol questions...

### ISSUE THREAD

**Issue by Dobie007** [Bro2111/WLAN-Klima#1]
First of all thanks for the nice implementation!   I have your software running on my Kesser AC - the web communication is working well. Now i am struggling to get the mqtt interface to Openhab: To get there i am trying to get the system to respond using the mqtt explorer:  In the picture you can see what i manged to do: If I post a message to the topic "Klima/Wohnzimmer/klima-in"
I get an answer under "Antwort:...   
![grafik](https://github.com/Bro2111/WLAN-Klima/assets/59510536/c8c18195-5018-404a-8df4-e5e56543dc0c)
I have tried all sorts of messages but get no response from the AC or Web interface.
A little help or a note in the documentation would be nice. Thanks

**Comment by Bro2111** [comment]
Hallo, you have to send a full secquence!

iStart = 1;               // 1- On ; 0 -Off
iTemperaturMqtt = 21;      //Temperatur
iModusMqtt = 131;          //Modus (Heat (1), dehum (2), cool (3) , Venting (7), Auto (8) Ventilator Mute (128))  Byte 8 (Swing?) is not immplemented 
iAirMqtt = 4;              //Ventilator speed (Auto (0), 
iSettingMqtt = 132;        //Summe aus Eco Ein (128), Display Ein (64), Buzzer Ein (32) + EIN (4)

for example, 1,21,1,0,132, this means 1- On, 21- 21 °C temperature, 1 - Modus heating, 132 - Eco On (128) + On (4)

Sorry for my late answer!

best regards Thomas

**Comment by Dobie007** [comment]
Thanks!

**Comment by Dobie007** [comment]
Thanks!
